Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Amazon Timestream Configuration"
        Parameters:
          - DbInstanceName

Parameters:
  DbInstanceName:
    Description: The name that uniquely identifies the DB instance when interacting with the Amazon Timestream . DB instance names must be unique per customer and per region.
    Type: String
    Default: mydbinstance
    MinLength: 3
    MaxLength: 40
    AllowedPattern: ^[a-zA-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*$

Resources:
  DbInstance:
    Type: AWS::Timestream::Database
    Properties:
      DatabaseName: !Ref DbInstanceName

  CommandRunner:
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties: 
        Command: 'pwd'

Outputs:
  DbInstance:
    Description: A reference to the Timestream DB instance
    Value: !Ref DbInstance
